version: '3.1'
services:

    db:
        image: mysql:8.4
        command: --mysql-native-password=ON
        restart: always
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./mysql_init_scripts:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 123
        ports:
            - 3306:3306
            
    adminer:
        image: adminer
        ports:
            - 8080:8080